# Generated by Django 3.1.3 on 2020-12-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='name',
        ),
    ]
