# Generated by Django 3.1.3 on 2020-12-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_auto_20201202_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='author',
        ),
    ]
